name: Euros 2024

on:
  schedule:
    # Run daily at 11:30 PM UTC (which is 5 AM IST)
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'  # or the version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas==1.5.1 pydantic==2.4.2 selenium==4.14.0 supabase==2.0.3 psycopg2-binary==2.9.9 bs4==0.0.1

    - name: Run Jupyter Notebook
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
      run: |
        jupyter nbconvert --to notebook --execute whoscored_final.ipynb --output whoscored_final_output.ipynb
